### ISSUE TITLE
Python 2 and 3

### ISSUE THREAD

**Issue by sebastian-luna-valero** [glarocca/pyEGI-AAI-CheckIn#4]
Hi,

I see we have Python 2 and 3 variants of the script.

Is there a reason to maintain the Python 2 version? Can we go ahead with only the Python 3 version?

I am here to help if needs be.

Best regards,
Sebastian

**Comment by glarocca** [comment]
Hi Sebastian,
The first commit was 2 years old. There is no reason to keep old Python version.
Cheers, Giuseppe
